//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierManagement.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class City_Price_Details
    {
        public int City_Id { get; set; }
        public string Source_City { get; set; }
        public string Destination_City { get; set; }
        public double Cost { get; set; }
    }
}
