//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierManagement.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment_Status
    {
        public int Status_id { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ExpectedDelivery { get; set; }
        public Nullable<int> Consignment_Id { get; set; }
        public Nullable<int> Delivery_Id { get; set; }
    
        public virtual Consignment Consignment { get; set; }
        public virtual Delivery_Executive Delivery_Executive { get; set; }
    }
}
