//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierManagement.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consignment()
        {
            this.Consignment_Status = new HashSet<Consignment_Status>();
            this.Delivery_Executive = new HashSet<Delivery_Executive>();
        }
    
        public int Consignment_Id { get; set; }
        public string Consignment_Type { get; set; }
        public double Weight { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public double Billing_Amount { get; set; }
        public Nullable<int> Consignee_Id { get; set; }
        public Nullable<int> Consigner_Id { get; set; }
    
        public virtual Consignee Consignee { get; set; }
        public virtual Consigner Consigner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consignment_Status> Consignment_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Executive> Delivery_Executive { get; set; }
    }
}
