//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierManagement.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Executive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery_Executive()
        {
            this.DStatus = "Available";
            this.MaxQty = 0;
            this.Consignment_Status = new HashSet<Consignment_Status>();
        }
    
        public int Delivery_Id { get; set; }
        public Nullable<int> Consignment_Id { get; set; }
        public string DE_Email { get; set; }
        public string Contact_number { get; set; }
        public string Name { get; set; }
        public string DStatus { get; set; }
        public string City { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public string DE_Password { get; set; }
    
        public virtual Consignment Consignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consignment_Status> Consignment_Status { get; set; }
    }
}
